"""timescale tables
Revision ID: 71e23840b9c2
Revises: e6abd9e054e7
Create Date: 2025-06-24 19:26:00.185263
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e23840b9c2'
down_revision: Union[str, None] = 'e6abd9e054e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_timescale',
    sa.Column('ticker', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('backtest_result_timescale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('backtest_result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_result_id'], ['backtest_result.id'], ),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_result_timescale')
    op.drop_table('stock_timescale')
    # ### end Alembic commands ###