"""made name non unique in portfolio

Revision ID: 7cddf136723a
Revises: fc6b3e2f29a3
Create Date: 2025-07-06 18:04:40.529098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cddf136723a'
down_revision: Union[str, None] = 'fc6b3e2f29a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('portfolio_name_key'), 'portfolio', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('portfolio_name_key'), 'portfolio', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###