"""made lastname not nullable

Revision ID: b8787f8c2b4f
Revises: 71e23840b9c2
Create Date: 2025-06-24 19:55:06.953522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8787f8c2b4f'
down_revision: Union[str, None] = '71e23840b9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('backtest_result_timescale_date_idx'), table_name='backtest_result_timescale')
    op.drop_index(op.f('stock_timescale_date_idx'), table_name='stock_timescale')
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('stock_timescale_date_idx'), 'stock_timescale', [sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('backtest_result_timescale_date_idx'), 'backtest_result_timescale', [sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###